csharp/movieproject/Models/Video.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace movieproject.Models
{
    public class Video
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Genre Genre { get; set; }
    }
    public enum Genre
    {
        Comedy = 1,
        Horror,
        SciFi,
        Romance,
        Documentary,
        Drama, 
        Action,
        Mystery
    }
}

csharp/movieproject/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using movieproject.Models;

namespace movieproject.Controllers
{

    public class VideosController : Controller
    {
        private ApplicationDbContext _dbContext;


        public VideosController()
        {
            _dbContext = new ApplicationDbContext();
        }
        // GET: Videos
        public ActionResult Index()
        {
            var videos = _dbContext.Videos.ToList();
            return View(videos);
        }
        public ActionResult New()
        {
            return View();
        }
        public ActionResult Add(Video video)
        {
            _dbContext.Videos.Add(video);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult Edit(int id)
        {
            var video = _dbContext.Videos.SingleOrDefault(v => v.Id == id);

            if (video == null)
                return HttpNotFound();

            return View(video);
        }
        [HttpPost]
        public ActionResult Update(Video video)
        {
            var videoInDb = _dbContext.Videos.SingleOrDefault(v => v.Id == video.Id);

            if (videoInDb == null)
                return HttpNotFound();

            videoInDb.Title = video.Title;
            videoInDb.Description = video.Description;
            videoInDb.Genre = video.Genre;
            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult Delete (int id)
        {
            var video = _dbContext.Videos.SingleOrDefault(v => v.Id == id);

            if (video == null)
                return HttpNotFound();

            return View(video);
        }
        [HttpPost]
        public ActionResult DoDelete(int id)
        {
            var video = _dbContext.Videos.SingleOrDefault(v => v.Id == id);

            if (video == null)
                return HttpNotFound();
            _dbContext.Videos.Remove(video);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");

        }


    }
}

csharp/movieproject/Views/Videos/Delete.cshtml
@model movieproject.Models.Video
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>
<p>
    Are you sure you would like to delete this video?
</p>
<ul>
    <li>Title: @Model.Title</li>
    <li>Description: @Model.Description</li>
</ul>
@using (Html.BeginForm("DoDelete", "Videos", FormMethod.Post))
{

    @Html.HiddenFor(m => m.Id)
    <input type="submit" class="btn btn-danger" value="Yes, Delete it!" />
    @Html.ActionLink("No, back to videos", "Index")
}

csharp/movieproject/Views/Videos/Edit.cshtml
@using (Html.BeginForm("Add", "Videos", FormMethod.Post, new { @class = "form" }))
{
    Html.RenderPartial("_VideoForm");
}

csharp/movieproject/Views/Videos/Index.cshtml
@model IEnumerable<movieproject.Models.Video>
    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>Videos</h2>
<p>
    @Html.ActionLink("Add Video", "New")
</p>
<ul>
    @foreach (var video in Model)
    {
        <li>
          @video.Title (@video.Genre) @Html.ActionLink("Edit", "Edit", new { id = video.Id }) |
          @Html.ActionLink("Delete", "Delete", new  { id = video.Id})
        </li>
    }
</ul>

csharp/movieproject/Views/Videos/New.cshtml
@model movieproject.Models.Video
@{    
   ViewBag.Title = "New";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New</h2>
@using (Html.BeginForm("Add", "Videos", FormMethod.Post, new { @class = "form" }))
{
    Html.RenderPartial("_VideoForm");
}